[package]
name = "zen-settings"
version.workspace = true
description = "Settings for the ZEN compositor"
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
adw = { version = "0.8.1", package = "libadwaita", features = ["v1_4"] }
anyhow.workspace = true
gtk = { version = "0.10.3", package = "gtk4", features = ["v4_12"] }
kdl = "4.7"
zen-config = { version = "0.1.0", path = "../zen-config" }
