#!/usr/bin/env bash
# Regenerates resources/theme-history.txt: every version of every shipped dotfile
# that ZEN has ever committed, by content hash.
#
# setup.sh uses it to tell "a config ZEN installed and the user never touched"
# from "a config the user wrote", so a fix to a shipped theme can reach someone
# who already has the broken copy without ever overwriting their own work.
#
# Run it after changing anything in resources/ that theme_file installs, and
# commit the result. tests/theme-history.sh checks it is current.
set -euo pipefail
cd "$(dirname "$0")/.."

# Derived from setup.sh rather than listed here. A second list would drift the moment a
# theme was added, and the drift is silent: the new theme just never becomes updatable.
FILES=$(grep -oE 'theme_file [^ ]+ +resources/[^ ]+' setup.sh | awk '{print $3}' | sort -u)
[ -n "$FILES" ] || { echo "found no theme_file calls in setup.sh" >&2; exit 1; }

{
    echo "# generated by scripts/theme-history.sh, do not edit"
    for f in $FILES; do
        {
            [ -f "$f" ] && sha256sum < "$f" | cut -d' ' -f1
            git log --format=%H -- "$f" | while read -r c; do
                git cat-file -p "$c:$f" 2>/dev/null | sha256sum | cut -d' ' -f1
            done
        } | sort -u | while read -r h; do
            [ -n "$h" ] && echo "$f $h"
        done
    done
} > resources/theme-history.txt

echo "wrote resources/theme-history.txt ($(grep -c . resources/theme-history.txt) lines)"
